完善一下

diff --git a/lmd b/lmd
--- a/lmd
+++ b/lmd
@@ -26,31 +26,38 @@ GREEN='\033[32m'
 YELLOW='\033[33m'
 RESET='\033[0m'
 
-AllowScriptDependencies() {
-    os_name=$(awk -F '=' '/^NAME/{print $2}' /etc/os-release | tr -d '"' | awk '{$1=$1};1')
-    os_architecture=$(uname -m)
+os_name=$(awk -F '=' '/^NAME/{print $2}' /etc/os-release | tr -d '"' | awk '{$1=$1};1')
+os_architecture=$(uname -m)
 
-    case "$os_name" in
+AllowScriptDependencies() {
+
+    case "${os_name}" in
         "Ubuntu")
-            dpkg -i install-denpend/files/sshpass_$os_architecture.deb
+            apt-get update 
+            apt-get install -y curl
+            dpkg -i install-denpend/files/sshpass_${os_architecture}.deb
             ;;
         "EulerOS")
-            rpm -ivh install-denpend/files/sshpass_$os_architecture.rpm
+            yum install -y curl
+            rpm -ivh install-denpend/files/sshpass_${os_architecture}.rpm
             ;;
         *)
-            echo -e "${RED} Unsupported OS: $os_name ${RESET}"
+            echo -e "${RED} Unsupported OS: ${os_name} ${RESET}"
             exit 1
             ;;
     esac
 
     # 安装 miniconda
-    wget -c -q -O /tmp/lmd/miniconda.sh https://mirror.nju.edu.cn/anaconda/miniconda/Miniconda3-py310_24.5.0-0-Linux-$os_architecture.sh
+    condaURL="https://mirror.nju.edu.cn/anaconda/miniconda/Miniconda3-py310_24.5.0-0-Linux-${os_architecture}.sh"
+    condaName="/tmp/miniconda.sh"
+    download "${condaURL}" "${condaName}"
     yes|bash /tmp/miniconda.sh -b -u -p /tmp/lmd/miniconda
 
     # 安装 ansible
     /tmp/lmd/miniconda/bin/python3.10 -m pip config set global.index-url https://mirror.nju.edu.cn/pypi/web/simple
     /tmp/lmd/miniconda/bin/python3.10 -m pip install --upgrade --no-cache-dir ansible
 }
+
 
 ScriptConfigurationDependency() {
     if [ ! -f ./inventory ]; then
@@ -63,6 +70,30 @@ ScriptConfigurationDependency() {
         exit 1
     fi
 }
+
+download() {
+    set +e
+
+    local max_retries=10
+    local retry_delay=10
+    local url=$1
+    local path=$2
+
+    for ((i=1; i<=max_retries; i++)); do
+        echo "Attempt $i of $max_retries..."
+        curl -fsSL -o "${path}" "${url}"
+        if [[ $? -eq 0 ]]; then
+            return 0
+        else
+            echo "Download failed with error code $?. Retrying in ${retry_delay} seconds..."
+            sleep ${retry_delay}
+        fi
+    done
+
+    echo "All attempts failed. Exiting."
+    return 1
+}
+
 
 install() {
     ScriptConfigurationDependency
@@ -78,8 +109,6 @@ uninstall() {
 }
 
 clear() {
-    os_name=$(awk -F '=' '/^NAME/{print $2}' /etc/os-release | tr -d '"' | awk '{$1=$1};1')
-    os_architecture=$(uname -m)
 
     case "$os_name" in
         "Ubuntu")
@@ -109,7 +138,7 @@ main() {
         install)
             echo -e "${YELLOW}是否已经阅读过 README.md 文件？[yY/nN] ${RESET}"
             read choice
-            case "$choice" in
+            case "${choice}" in
                 y|Y )
                     install
                     ;;
@@ -122,7 +151,7 @@ main() {
         uninstall)
             echo -e "${YELLOW}是否已经阅读过 README.md 文件？[yY/nN] ${RESET}"
             read choice
-            case "$choice" in
+            case "${choice}" in
                 y|Y )
                     uninstall
                     ;;
